export const grades = [
    { value: "V0-", label: "V0-", french: "4-", gradeValue: 0, ranking: 1 },
    { value: "V0", label: "V0", french: "4", gradeValue: 0, ranking: 2 },
    { value: "V0+", label: "V0+", french: "4+", gradeValue: 0, ranking: 3 },
    { value: "V0/1", label: "V0/1", french: "4+", gradeValue: 0, ranking: 4 },
    { value: "V1-", label: "V1-", french: "5-", gradeValue: 1, ranking: 5 },
    { value: "V1", label: "V1", french: "5", gradeValue: 1, ranking: 6 },
    { value: "V1+", label: "V1+", french: "5", gradeValue: 1, ranking: 7 },
    { value: "V1/2", label: "V1/2", french: "5", gradeValue: 1, ranking: 8 },
    { value: "V2-", label: "V2-", french: "5+", gradeValue: 2, ranking: 9 },
    { value: "V2", label: "V2", french: "5+", gradeValue: 2, ranking: 10 },
    { value: "V2+", label: "V2+", french: "5+", gradeValue: 2, ranking: 11 },
    { value: "V2/3", label: "V2/3", french: "5+", gradeValue: 2, ranking: 12 },
    { value: "V3-", label: "V3-", french: "6A", gradeValue: 3, ranking: 13 },
    { value: "V3", label: "V3", french: "6A", gradeValue: 3, ranking: 14 },
    { value: "V3+", label: "V3+", french: "6A+", gradeValue: 3, ranking: 15 },
    { value: "V3/4", label: "V3/4", french: "6A+", gradeValue: 3, ranking: 16 },
    { value: "V4-", label: "V4-", french: "6B", gradeValue: 4, ranking: 17 },
    { value: "V4", label: "V4", french: "6B", gradeValue: 4, ranking: 18 },
    { value: "V4+", label: "V4+", french: "6B+", gradeValue: 4, ranking: 19 },
    { value: "V4/5", label: "V4/5", french: "6B+", gradeValue: 4, ranking: 20 },
    { value: "V5-", label: "V5-", french: "6C", gradeValue: 5, ranking: 21 },
    { value: "V5", label: "V5", french: "6C", gradeValue: 5, ranking: 22 },
    { value: "V5+", label: "V5+", french: "6C+", gradeValue: 5, ranking: 23 },
    { value: "V5/6", label: "V5/6", french: "6C+", gradeValue: 5, ranking: 24 },
    { value: "V6-", label: "V6-", french: "7A", gradeValue: 6, ranking: 25 },
    { value: "V6", label: "V6", french: "7A", gradeValue: 6, ranking: 26 },
    { value: "V6+", label: "V6+", french: "7A", gradeValue: 6, ranking: 27 },
    { value: "V6/7", label: "V6/7", french: "7A+", gradeValue: 6, ranking: 28 },
    { value: "V7-", label: "V7-", french: "7A+", gradeValue: 7, ranking: 29 },
    { value: "V7", label: "V7", french: "7A+", gradeValue: 7, ranking: 30 },
    { value: "V7+", label: "V7+", french: "7A+", gradeValue: 7, ranking: 31 },
    { value: "V7/8", label: "V7/8", french: "7B", gradeValue: 7, ranking: 32 },
    { value: "V8-", label: "V8-", french: "7B", gradeValue: 8, ranking: 33 },
    { value: "V8", label: "V8", french: "7B", gradeValue: 8, ranking: 34 },
    { value: "V8+", label: "V8+", french: "7B+", gradeValue: 8, ranking: 35 },
    { value: "V8/9", label: "V8/9", french: "7B+", gradeValue: 8, ranking: 36 },
    { value: "V9-", label: "V9-", french: "7C", gradeValue: 9, ranking: 37 },
    { value: "V9", label: "V9", french: "7C", gradeValue: 9, ranking: 38 },
    { value: "V9+", label: "V9+", french: "7C", gradeValue: 9, ranking: 39 },
    {
        value: "V9/10",
        label: "V9/10",
        french: "7C+",
        gradeValue: 9,
        ranking: 40,
    },
    {
        value: "V10-",
        label: "V10-",
        french: "7C+",
        gradeValue: 10,
        ranking: 41,
    },
    { value: "V10", label: "V10", french: "7C+", gradeValue: 10, ranking: 42 },
    {
        value: "V10+",
        label: "V10+",
        french: "7C+",
        gradeValue: 10,
        ranking: 43,
    },
    {
        value: "V10/11",
        label: "V10/11",
        french: "8A",
        gradeValue: 10,
        ranking: 44,
    },
    { value: "V11-", label: "V11-", french: "8A", gradeValue: 11, ranking: 45 },
    { value: "V11", label: "V11", french: "8A", gradeValue: 11, ranking: 46 },
    { value: "V11+", label: "V11+", french: "8A", gradeValue: 11, ranking: 47 },
    {
        value: "V11/12",
        label: "V11/12",
        french: "8A+",
        gradeValue: 11,
        ranking: 48,
    },
    {
        value: "V12-",
        label: "V12-",
        french: "8A+",
        gradeValue: 12,
        ranking: 49,
    },
    { value: "V12", label: "V12", french: "8A+", gradeValue: 12, ranking: 50 },
    {
        value: "V12+",
        label: "V12+",
        french: "8A+",
        gradeValue: 12,
        ranking: 51,
    },
    {
        value: "V12/13",
        label: "V12/13",
        french: "8B",
        gradeValue: 12,
        ranking: 52,
    },
    { value: "V13-", label: "V13-", french: "8B", gradeValue: 13, ranking: 53 },
    { value: "V13", label: "V13", french: "8B", gradeValue: 13, ranking: 54 },
    { value: "V13+", label: "V13+", french: "8B", gradeValue: 13, ranking: 55 },
    {
        value: "V13/14",
        label: "V13/14",
        french: "8B+",
        gradeValue: 13,
        ranking: 56,
    },
    {
        value: "V14-",
        label: "V14-",
        french: "8B+",
        gradeValue: 14,
        ranking: 57,
    },
    { value: "V14", label: "V14", french: "8B+", gradeValue: 14, ranking: 58 },
    {
        value: "V14+",
        label: "V14+",
        french: "8B+",
        gradeValue: 14,
        ranking: 59,
    },
    {
        value: "V14/15",
        label: "V14/15",
        french: "8C",
        gradeValue: 14,
        ranking: 60,
    },
    { value: "V15-", label: "V15-", french: "8C", gradeValue: 15, ranking: 61 },
    { value: "V15", label: "V15", french: "8C", gradeValue: 15, ranking: 62 },
    { value: "V15+", label: "V15+", french: "8C", gradeValue: 15, ranking: 63 },
    {
        value: "V15/16",
        label: "V15/16",
        french: "8C+",
        gradeValue: 15,
        ranking: 64,
    },
    {
        value: "V16-",
        label: "V16-",
        french: "8C+",
        gradeValue: 16,
        ranking: 65,
    },
    { value: "V16", label: "V16", french: "8C+", gradeValue: 16, ranking: 66 },
    {
        value: "V16+",
        label: "V16+",
        french: "8C+",
        gradeValue: 16,
        ranking: 67,
    },
    {
        value: "V16/17",
        label: "V16/17",
        french: "9A",
        gradeValue: 16,
        ranking: 68,
    },
    { value: "V17-", label: "V17-", french: "9A", gradeValue: 17, ranking: 69 },
    { value: "V17", label: "V17", french: "9A", gradeValue: 17, ranking: 70 },
];
