export const locations = [
    {
        id: 1,
        label: "The Pad Henderson",
        location: "Henderson",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHwdry8EZH9GFr7bgu28kpqA3cRa6WenvwdOJM",
    },
    {
        id: 2,
        label: "Refuge Climbing & Fitness",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
    },
    {
        id: 3,
        label: "Red Rock Climbing Center",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
    },
    {
        id: 4,
        label: "Kraft Boulders",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHxeJh2qV9a6jXxUs2gBWczRKwbpYEI3k5Dql1",
    },
    {
        id: 5,
        label: "Red Springs",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH2T7oP47YXmGBJlOSW6co9ifbKCQwqp8Nad4n",
    },
    {
        id: 6,
        label: "Calico Basin",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 7,
        label: "Willow Springs",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 8,
        label: "Black Velvet Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 9,
        label: "Oak Creek Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 10,
        label: "Pine Creek Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 11,
        label: "UNLV",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Indoors",
    },
    {
        id: 12,
        label: "Nevada Climbing Center",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Indoors",
    },
    {
        id: 13,
        label: "Mount Charleston",
        location: "Mount Charleston",
        country: "USA",
        state: "NV",
        type: "Outdoors",
    },
    {
        id: 14,
        label: "Gateway Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH7FXYftmNGmcJQhp0sP1SDFXOtxnwRTeZ56za",
    },
    {
        id: 15,
        label: "The Buttermilks",
        location: "Bishop",
        country: "USA",
        state: "CA",
        type: "Outdoors",
    },
];
