export const locations = [
    {
        id: 1,
        label: "The Pad Henderson",
        location: "Henderson",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHwdry8EZH9GFr7bgu28kpqA3cRa6WenvwdOJM",
    },
    {
        id: 2,
        label: "Refuge Climbing & Fitness",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHZ5VAvtFROTl1mJfh9wAu8gn4H30SEFXVGs6r",
    },
    {
        id: 3,
        label: "Red Rock Climbing Center",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHLvT7xFN8zPOm7K2qZuBpbQtRNkEd9gc8jWsa",
    },
    {
        id: 4,
        label: "Kraft Boulders",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHxeJh2qV9a6jXxUs2gBWczRKwbpYEI3k5Dql1",
    },
    {
        id: 5,
        label: "Red Springs",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH2T7oP47YXmGBJlOSW6co9ifbKCQwqp8Nad4n",
    },
    {
        id: 6,
        label: "Calico Basin",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHmjgxCoROQt0LIls1WGRXPeBDziudwrFkChfO",
    },
    {
        id: 7,
        label: "Willow Springs",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHsucxDGEtiTbfYFSx6H9KqOwAdP5pI2yJzGQg",
    },
    {
        id: 8,
        label: "Black Velvet Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHUdBwej9fzToEbCZXMuwHcNPjI4emvBg02DS5",
    },
    {
        id: 9,
        label: "Oak Creek Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH1ZMMC8gpRqLucd5UgoznXWAFBkxEjvmDOKSY",
    },
    {
        id: 10,
        label: "Pine Creek Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHhUi0O7pW3bNFlP6CuEBOXgpRfiqjQcxZ9VmT",
    },
    {
        id: 11,
        label: "UNLV",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHqzh68UvAOuQ7MnWNRIVdhjsK2atZrYlbwBS1",
    },
    {
        id: 12,
        label: "Nevada Climbing Center",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Indoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHhS2wuVpW3bNFlP6CuEBOXgpRfiqjQcxZ9VmT",
    },
    {
        id: 13,
        label: "Mount Charleston",
        location: "Mount Charleston",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH7PgFYLMmNGmcJQhp0sP1SDFXOtxnwRTeZ56z",
    },
    {
        id: 14,
        label: "Gateway Canyon",
        location: "Red Rock",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZH7FXYftmNGmcJQhp0sP1SDFXOtxnwRTeZ56za",
    },
    {
        id: 15,
        label: "The Buttermilks",
        location: "Bishop",
        country: "USA",
        state: "CA",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHgjMiOyJtHJruA2l4oT7RbqG1LkiWNjESUM6v",
    },
    {
        id: 16,
        label: "Happy Boulders",
        location: "Bishop",
        country: "USA",
        state: "CA",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHGa111uwmcU07IRMTLbAiaqw12YdOsEyPvz6W",
    },
    {
        id: 17,
        label: "Sad Boulders",
        location: "Bishop",
        country: "USA",
        state: "CA",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHWOngGS5uveCYybtB3p9woHzrUMjFmnE1dAZa",
    },
    {
        id: 18,
        label: "Joshua Tree",
        location: "Twentynine Palms",
        country: "USA",
        state: "CA",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHRCWYtZlXlQ8EVBW219wxTzckP0JNdhHtmRv4",
    },
    {
        id: 19,
        label: "Big Sandy",
        location: "Henderson",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHEn0F0BQWUIAe2LQRmznslHjVBNTMfJXyD4qd",
    },
    {
        id: 20,
        label: "Red Rock Canyon",
        location: "Las Vegas",
        country: "USA",
        state: "NV",
        type: "Outdoors",
        image: "https://utfs.io/f/lXqKHYWPgVZHT1lmHWUAq7NEiOuvrek46SWxltIg1QsjJ5CF",
    },
];
