export const yds = [
    { value: "5.0", label: "5.0", french: "2-", gradeValue: 0, ranking: 0 },
    { value: "5.1", label: "5.1", french: "2", gradeValue: 1, ranking: 1 },
    { value: "5.2", label: "5.2", french: "3", gradeValue: 2, ranking: 2 },
    { value: "5.3", label: "5.3", french: "3+", gradeValue: 3, ranking: 3 },
    { value: "5.4", label: "5.4", french: "4a", gradeValue: 4, ranking: 4 },
    { value: "5.5", label: "5.5", french: "4b", gradeValue: 5, ranking: 5 },
    { value: "5.6", label: "5.6", french: "4c", gradeValue: 6, ranking: 6 },
    { value: "5.7", label: "5.7", french: "5a", gradeValue: 7, ranking: 7 },
    { value: "5.7+", label: "5.7+", french: "5a", gradeValue: 7, ranking: 8 },
    { value: "5.8-", label: "5.8-", french: "5b", gradeValue: 8, ranking: 9 },
    { value: "5.8", label: "5.8", french: "5b", gradeValue: 8, ranking: 10 },
    { value: "5.8+", label: "5.8+", french: "5b", gradeValue: 8, ranking: 11 },
    { value: "5.9-", label: "5.9-", french: "5c", gradeValue: 9, ranking: 12 },
    { value: "5.9", label: "5.9", french: "5c", gradeValue: 9, ranking: 13 },
    { value: "5.9+", label: "5.9+", french: "5c", gradeValue: 9, ranking: 14 },
    {
        value: "5.10a",
        label: "5.10a",
        french: "6a",
        gradeValue: 10,
        ranking: 15,
    },
    {
        value: "5.10-",
        label: "5.10-",
        french: "6a",
        gradeValue: 10,
        ranking: 16,
    },
    {
        value: "5.10a/b",
        label: "5.10a/b",
        french: "6a+",
        gradeValue: 10,
        ranking: 17,
    },
    {
        value: "5.10b",
        label: "5.10b",
        french: "6a+",
        gradeValue: 10,
        ranking: 18,
    },
    { value: "5.10", label: "5.10", french: "6b", gradeValue: 10, ranking: 19 },
    {
        value: "5.10b/c",
        label: "5.10b/c",
        french: "6b",
        gradeValue: 10,
        ranking: 20,
    },
    {
        value: "5.10c",
        label: "5.10c",
        french: "6b",
        gradeValue: 10,
        ranking: 21,
    },
    {
        value: "5.10+",
        label: "5.10+",
        french: "6b+",
        gradeValue: 10,
        ranking: 22,
    },
    {
        value: "5.10c/d",
        label: "5.10c/d",
        french: "6b+",
        gradeValue: 10,
        ranking: 23,
    },
    {
        value: "5.10d",
        label: "5.10d",
        french: "6b+",
        gradeValue: 10,
        ranking: 24,
    },
    {
        value: "5.11a",
        label: "5.11a",
        french: "6c",
        gradeValue: 11,
        ranking: 25,
    },
    {
        value: "5.11-",
        label: "5.11-",
        french: "6c",
        gradeValue: 11,
        ranking: 26,
    },
    {
        value: "5.11a/b",
        label: "5.11a/b",
        french: "6c",
        gradeValue: 11,
        ranking: 27,
    },
    {
        value: "5.11b",
        label: "5.11b",
        french: "6c",
        gradeValue: 11,
        ranking: 28,
    },
    {
        value: "5.11",
        label: "5.11",
        french: "6c+",
        gradeValue: 11,
        ranking: 29,
    },
    {
        value: "5.11b/c",
        label: "5.11b/c",
        french: "6c+",
        gradeValue: 11,
        ranking: 30,
    },
    {
        value: "5.11c",
        label: "5.11c",
        french: "6c+",
        gradeValue: 11,
        ranking: 31,
    },
    {
        value: "5.11+",
        label: "5.11+",
        french: "7a",
        gradeValue: 11,
        ranking: 32,
    },
    {
        value: "5.11c/d",
        label: "5.11c/d",
        french: "7a",
        gradeValue: 11,
        ranking: 33,
    },
    {
        value: "5.11d",
        label: "5.11d",
        french: "7a",
        gradeValue: 11,
        ranking: 34,
    },
    {
        value: "5.12a",
        label: "5.12a",
        french: "7a+",
        gradeValue: 12,
        ranking: 35,
    },
    {
        value: "5.12-",
        label: "5.12-",
        french: "7a+",
        gradeValue: 12,
        ranking: 36,
    },
    {
        value: "5.12a/b",
        label: "5.12a/b",
        french: "7b",
        gradeValue: 12,
        ranking: 37,
    },
    {
        value: "5.12b",
        label: "5.12b",
        french: "7b",
        gradeValue: 12,
        ranking: 38,
    },
    {
        value: "5.12",
        label: "5.12",
        french: "7b+",
        gradeValue: 12,
        ranking: 39,
    },
    {
        value: "5.12b/c",
        label: "5.12b/c",
        french: "7b+",
        gradeValue: 12,
        ranking: 40,
    },
    {
        value: "5.12c",
        label: "5.12c",
        french: "7b+",
        gradeValue: 12,
        ranking: 41,
    },
    {
        value: "5.12+",
        label: "5.12+",
        french: "7c",
        gradeValue: 12,
        ranking: 42,
    },
    {
        value: "5.12c/d",
        label: "5.12c/d",
        french: "7c",
        gradeValue: 12,
        ranking: 43,
    },
    {
        value: "5.12d",
        label: "5.12d",
        french: "7c",
        gradeValue: 12,
        ranking: 44,
    },
    {
        value: "5.13a",
        label: "5.13a",
        french: "7c+",
        gradeValue: 13,
        ranking: 45,
    },
    {
        value: "5.13-",
        label: "5.13-",
        french: "7c+",
        gradeValue: 13,
        ranking: 46,
    },
    {
        value: "5.13a/b",
        label: "5.13a/b",
        french: "8a",
        gradeValue: 13,
        ranking: 47,
    },
    {
        value: "5.13b",
        label: "5.13b",
        french: "8a",
        gradeValue: 13,
        ranking: 48,
    },
    { value: "5.13", label: "5.13", french: "8a", gradeValue: 13, ranking: 49 },
    {
        value: "5.13b/c",
        label: "5.13b/c",
        french: "8a+",
        gradeValue: 13,
        ranking: 50,
    },
    {
        value: "5.13c",
        label: "5.13c",
        french: "8a+",
        gradeValue: 13,
        ranking: 51,
    },
    {
        value: "5.13+",
        label: "5.13+",
        french: "8b",
        gradeValue: 13,
        ranking: 52,
    },
    {
        value: "5.13c/d",
        label: "5.13c/d",
        french: "8b",
        gradeValue: 13,
        ranking: 53,
    },
    {
        value: "5.13d",
        label: "5.13d",
        french: "8b",
        gradeValue: 13,
        ranking: 54,
    },
    {
        value: "5.14a",
        label: "5.14a",
        french: "8b+",
        gradeValue: 14,
        ranking: 55,
    },
    {
        value: "5.14-",
        label: "5.14-",
        french: "8b+",
        gradeValue: 14,
        ranking: 56,
    },
    {
        value: "5.14a/b",
        label: "5.14a/b",
        french: "8c",
        gradeValue: 14,
        ranking: 57,
    },
    {
        value: "5.14b",
        label: "5.14b",
        french: "8c",
        gradeValue: 14,
        ranking: 58,
    },
    {
        value: "5.14",
        label: "5.14",
        french: "8c+",
        gradeValue: 14,
        ranking: 59,
    },
    {
        value: "5.14b/c",
        label: "5.14b/c",
        french: "8c+",
        gradeValue: 14,
        ranking: 60,
    },
    {
        value: "5.14c",
        label: "5.14c",
        french: "8c+",
        gradeValue: 14,
        ranking: 61,
    },
    {
        value: "5.14+",
        label: "5.14+",
        french: "9a",
        gradeValue: 14,
        ranking: 62,
    },
    {
        value: "5.14c/d",
        label: "5.14c/d",
        french: "9a",
        gradeValue: 14,
        ranking: 63,
    },
    {
        value: "5.14d",
        label: "5.14d",
        french: "9a",
        gradeValue: 14,
        ranking: 64,
    },
    {
        value: "5.15a",
        label: "5.15a",
        french: "9a+",
        gradeValue: 15,
        ranking: 65,
    },
    {
        value: "5.15-",
        label: "5.15-",
        french: "9a+",
        gradeValue: 15,
        ranking: 66,
    },
    {
        value: "5.15a/b",
        label: "5.15a/b",
        french: "9a+",
        gradeValue: 15,
        ranking: 67,
    },
    {
        value: "5.15b",
        label: "5.15b",
        french: "9b",
        gradeValue: 15,
        ranking: 68,
    },
    { value: "5.15", label: "5.15", french: "9b", gradeValue: 15, ranking: 69 },
    {
        value: "5.15c",
        label: "5.15c",
        french: "9b+",
        gradeValue: 15,
        ranking: 61,
    },
    {
        value: "5.15+",
        label: "5.15+",
        french: "9b+",
        gradeValue: 15,
        ranking: 62,
    },
    {
        value: "5.15c/d",
        label: "5.15c/d",
        french: "9c",
        gradeValue: 15,
        ranking: 63,
    },
    {
        value: "5.15d",
        label: "5.15d",
        french: "9c",
        gradeValue: 15,
        ranking: 64,
    },
];
